export const LOAD_POST_IMAGE_REQUEST = "LOAD_POST_IMAGE_REQUEST";
export const LOAD_POST_IMAGE_SUCCESS = "LOAD_POST_IMAGE_SUCCESS";
export const LOAD_POST_IMAGE_FAILURE = "LOAD_POST_IMAGE_FAILURE";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export const LOAD_POSTS_REQUEST = "LOAD_POSTS_REQUEST";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE";
