//이미지 미리 불러오기
export const LOAD_POST_IMAGE_REQUEST = "LOAD_POST_IMAGE_REQUEST";
export const LOAD_POST_IMAGE_SUCCESS = "LOAD_POST_IMAGE_SUCCESS";
export const LOAD_POST_IMAGE_FAILURE = "LOAD_POST_IMAGE_FAILURE";

//게시글 추가
export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

//게시글 불러오기
export const LOAD_POSTS_REQUEST = "LOAD_POSTS_REQUEST";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE";

//게시글 좋아요
export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAILURE = "POST_LIKE_FAILURE";

//게시글 좋아요 취소
export const POST_LIKE_REMOVE_REQUEST = "POST_LIKE_REMOVE_REQUEST";
export const POST_LIKE_REMOVE_SUCCESS = "POST_LIKE_REMOVE_SUCCESS";
export const POST_LIKE_REMOVE_FAILURE = "POST_LIKE_REMOVE_FAILURE";

//댓글 추가
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

//댓글 불러오기
export const LOAD_COMMENTS_REQUEST = "LOAD_COMMENTS_REQUEST";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_FAILURE = "LOAD_COMMENTS_FAILURE";

//modal창 불러오기
export const LOAD_MODAL_POST_REQUEST = "LOAD_MODAL_POST_REQUEST";
export const LOAD_MODAL_POST_SUCCESS = "LOAD_MODAL_POST_SUCCESS";
export const LOAD_MODAL_POST_FAILURE = "LOAD_MODAL_POST_FAILURE";
