//회원가입
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

//로그인
export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

//로그아웃
export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";

//내 정보 로드
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

//유저 상세 페이지 정보
export const LOAD_USER_DETAIL_REQUEST = "LOAD_USER_DETAIL_REQUEST";
export const LOAD_USER_DETAIL_SUCCESS = "LOAD_USER_DETAIL_SUCCESS";
export const LOAD_USER_DETAIL_FAILURE = "LOAD_USER_DETAIL_FAILURE";

//프로필 사진 변경
export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

//유저 정보 변경
export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAILURE = "USER_EDIT_FAILURE";

//카카오 로그인
export const KAKAO_REQUEST = "KAKAO_REQUEST";
export const KAKAO_SUCCESS = "KAKAO_SUCCESS";
export const KAKAO_FAILURE = "KAKAO_FAILURE";

//팔로우
export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAILURE = "FOLLOW_FAILURE";

//언팔로우
export const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAILURE = "UNFOLLOW_FAILURE";

//팔로우 목록 불러오기
export const LOAD_FOLLOW_REQUEST = "LOAD_FOLLOW_REQUEST";
export const LOAD_FOLLOW_SUCCESS = "LOAD_FOLLOW_SUCCESS";
export const LOAD_FOLLOW_FAILURE = "LOAD_FOLLOW_FAILURE";

//팔로워 목록 불러오기
export const LOAD_FOLLOWER_REQUEST = "LOAD_FOLLOWER_REQUEST";
export const LOAD_FOLLOWER_SUCCESS = "LOAD_FOLLOWER_SUCCESS";
export const LOAD_FOLLOWER_FAILURE = "LOAD_FOLLOWER_FAILURE";

//유저 게시글 불러오기
export const LOAD_USER_POSTS_REQUEST = "LOAD_USER_POSTS_REQUEST";
export const LOAD_USER_POSTS_SUCCESS = "LOAD_USER_POSTS_SUCCESS";
export const LOAD_USER_POSTS_FAILURE = "LOAD_USER_POSTS_FAILURE";

//유저 저장 게시글 불러오기
export const LOAD_USER_SAVED_POSTS_REQUEST = "LOAD_USER_SAVED_POSTS_REQUEST";
export const LOAD_USER_SAVED_POSTS_SUCCESS = "LOAD_USER_SAVED_POSTS_SUCCESS";
export const LOAD_USER_SAVED_POSTS_FAILURE = "LOAD_USER_SAVED_POSTS_FAILURE";
